strict: true
site_name: py-optional
site_description: Optional value pattern for python.
site_url: https://francipvb.github.io/py-optional

theme:
    name: "material"

    features:
        - content.code.select
        - content.code.copy
repo_name: francipvb/py-optional
repo_url: https://github.com/francipvb/py-optional
edit_uri: ""

nav:
    - index.md
    - MOTIVATION.md
    - USAGE.md
    - api.md
    - CHANGELOG.md

plugins:
    - search
    - mkdocstrings
    - autorefs

watch:
    - "optional"

site_author: "Francisco Del Roio"
remote_branch: gh-pages
remote_name: origin

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
