name: Publish documentation

on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry~=1.8.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install Dependencies
        run: poetry install

      - name: Build documentation site
        run: |
          poetry run mkdocs gh-deploy
